/*globals define, WebGMEGlobal*/
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 0.1.0 from webgme on Sat Oct 10 2015 10:55:29 GMT-0500 (CDT).
 */

define([
    'js/Panels/ModelEditor/ModelEditorControl',
    'js/Controls/PropertyGrid/PropertyGrid',
    'js/Panels/PropertyEditor/PropertyEditorPanelController',
    'js/Constants',
    'text!./templates/InspectDialog.html'
], function (
    ModelEditorControl,
    PropertyGrid,
    PropertyEditorPanelController,
    CONSTANTS,
    InspectDialogHtml
) {

    'use strict';

    var CNNVizControl;

    CNNVizControl = function (options) {

        ModelEditorControl.call(this, options);

        this.logger = options.logger.fork('Control');
        this.logger.debug('ctor finished');

        var self = this;
        this.designerCanvas.showInspector = function(id) {
            var propertyGrid = new PropertyGrid(),
                // FIXME: Subclass PropertyEditorPanel and customize
                p = new PropertyEditorPanelController(self._client, propertyGrid, CONSTANTS.PROPERTY_GROUP_ATTRIBUTES),
                gmeId = self._ComponentID2GmeID[id];

            // create the modal dialog box
            p._selectObjectsUsingActiveObject(gmeId);
            self._dialog = $(InspectDialogHtml);
            self._dialog.find('#inspect-content').append(propertyGrid.$el);

            // Show the dialog box
            self._dialog.modal('show');
        };

    };

    _.extend(CNNVizControl.prototype, ModelEditorControl.prototype);

    return CNNVizControl;
});
