/*globals define, WebGMEGlobal*/
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 0.1.0 from webgme on Sat Oct 10 2015 10:55:29 GMT-0500 (CDT).
 */

define([
    'js/Panels/ModelEditor/ModelEditorControl'
], function (
    ModelEditorControl
) {

    'use strict';

    var CNNVizControl;

    CNNVizControl = function (options) {

        ModelEditorControl.call(this, options);

        this.logger = options.logger.fork('Control');
        this.logger.debug('ctor finished');
    };

    _.extend(CNNVizControl.prototype, ModelEditorControl.prototype);

    return CNNVizControl;
});
