/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 0.14.0 from webgme on Fri Sep 18 2015 09:17:18 GMT-0500 (CDT).
 */

define([
    'TemplateCreator/TemplateCreator',
    './CaffeOutputGenerator'
], function (SimpleNodes, CaffeTemplateCreator) {
    'use strict';

    /**
     * Initializes a new instance of CaffeGenerator.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin CaffeGenerator.
     * @constructor
     */
    var CaffeGenerator = function () {
        // Call base class' constructor.
        SimpleNodes.call(this);
        this.generator = new CaffeTemplateCreator();
    };

    // Prototypal inheritance from PluginBase.
    CaffeGenerator.prototype = Object.create(SimpleNodes.prototype);
    CaffeGenerator.prototype.constructor = CaffeGenerator;

    /**
     * Gets the name of the CaffeGenerator.
     * @returns {string} The name of the plugin.
     * @public
     */
    CaffeGenerator.prototype.getName = function () {
        return 'Caffe Generator';
    };

    /**
     * Gets the semantic version (semver.org) of the CaffeGenerator.
     * @returns {string} The version of the plugin.
     * @public
     */
    CaffeGenerator.prototype.getVersion = function () {
        return '0.1.0';
    };

    CaffeGenerator.prototype.getConfigStructure = function(){
        // TODO: Add caffe specific training things here
        return [];
    };

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    CaffeGenerator.prototype.main = function (callback) {
        var self = this;

        // TODO: decorate the model with training info and update the
        // templates/output stuff for Caffe
        SimpleNodes.prototype.main.call(this, callback);
    };

    return CaffeGenerator;
});
