/*globals define, WebGMEGlobal*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 0.1.0 from webgme on Sat Oct 10 2015 10:55:29 GMT-0500 (CDT).
 */

define([
    'js/Widgets/DiagramDesigner/DiagramDesignerWidget',
    'js/Widgets/DiagramDesigner/DiagramDesignerWidget.Tabs',
    './SelectionManager',
    'css!./styles/CNNVizWidget.css'
], function (
    DiagramDesigner,
    DiagramDesignerTabs,
    SelectionManager
) {
    'use strict';

    var CNNVizWidget,
        WIDGET_CLASS = 'cnn-viz';

    CNNVizWidget = function (logger, container, options) {
        var selectionManager = new SelectionManager({widget: this}),
            options = {
                selectionManager: selectionManager
            };

        DiagramDesigner.call(this, container, options);

        // Override the DiagramDesigner logger and selection manager
        this.logger = logger.fork('Widget');

        this._dialog = null;
        this.logger.debug('ctor finished');
    };

    _.extend(CNNVizWidget.prototype, DiagramDesigner.prototype);

    CNNVizWidget.prototype._onSelectionCommandClicked = function(command, selectedIds, event) {
        switch (command) {
            case 'inspect':
                this.showInspector(selectedIds[0]);
                break;

            default:
                DiagramDesigner.prototype._onSelectionCommandClicked
                    .call(this, command, selectedIds, event);
                break;
        }
    };

    // Remove all tab functionality... it's a little hacky...
    var nop = function(){},
        tabMethods = Object.keys(DiagramDesignerTabs.prototype);
    tabMethods.forEach(method => CNNVizWidget.prototype[method] = nop);

    return CNNVizWidget;
});
